version: '3'

services:
  osis:
    ports:
      - "8000:8000"

    volumes:
      - ./osis:/app

    networks:
      - core

    build: ./osis/

    env_file:
      - ./osis/.env

    links:
      - db-osis
      - rabbit
      - redis

  osis-portal:
    volumes:
      - ./osis-portal/:/app
    ports:
      - "8001:8000"
    build: ./osis-portal/

    env_file:
      - ./osis-portal/.env

    networks:
      - portal

    links:
      - db-osis-portal:db-osis-portal
      - rabbit
      - redis

  db-osis:
    image: postgres:9.6
    restart: always
    env_file:
      - ./osis/.env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    networks:
      - core

  db-osis-portal:
    image: postgres:9.6
    restart: always
    env_file:
      - ./osis-portal/.env
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata-portal:/var/lib/postgresql/data/

    networks:
      - portal

  rabbit:
    image: rabbitmq
    networks:
      - core
      - portal

  redis:
    image: redis
    networks:
      - core
      - portal

networks:
  portal:
    driver: bridge

  core:
    driver: bridge
